### ISSUE TITLE
gulp giving the following error

### ISSUE THREAD

**Issue by MakeApps** [mrakodol/Laravel-5-Bootstrap-3-Starter-Site#119]
[12:26:20] Starting 'sass'...
[12:26:20] Running Sass: resources/assets/sass/site.scss
[12:26:20] Running Sass: resources/assets/sass/admin.scss
{ [Error: resources/assets/sass/site.scss
  2:9  file to import not found or unreadable: yeti/variables
Current dir: ]
  message: 'resources/assets/sass/site.scss\n  2:9  file to import not found or unreadable: yeti/variables\nCurrent dir: ',
  column: 9,
  line: 2,
  file: 'stdin',
  status: 1,
  messageFormatted: '\u001b[4mresources/assets/sass/site.scss\u001b[24m\n\u001b[90m  2:9\u001b[39m  file to import not found or unreadable: yeti/variables\nCurrent dir: ',
  name: 'Error',
  stack: 'Error: resources/assets/sass/site.scss\n  2:9  file to import not found or unreadable: yeti/variables\nCurrent dir: \n    at options.error (/home/rubyguy/public_html/lead_start/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
{ [Error: resources/assets/sass/admin.scss
  1:9  file to import not found or unreadable: yeti/variables
Current dir: ]
  message: 'resources/assets/sass/admin.scss\n  1:9  file to import not found or unreadable: yeti/variables\nCurrent dir: ',
  column: 9,
  line: 1,
  file: 'stdin',
  status: 1,
  messageFormatted: '\u001b[4mresources/assets/sass/admin.scss\u001b[24m\n\u001b[90m  1:9\u001b[39m  file to import not found or unreadable: yeti/variables\nCurrent dir: ',
  name: 'Error',
  stack: 'Error: resources/assets/sass/admin.scss\n  1:9  file to import not found or unreadable: yeti/variables\nCurrent dir: \n    at options.error (/home/rubyguy/public_html/lead_start/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[12:26:20] Finished 'sass' after 295 ms
[12:26:20] Starting 'styles'...
[12:26:20] Merging: resources/vendor/jquery-colorbox/example3/colorbox.css, resources/assets/build/site.css
[12:26:20] Merging: resources/vendor/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css, resources/vendor/metisMenu/dist/metisMenu.css, resources/assets/build/admin.css
[12:26:20] File not found: resources/vendor/jquery-colorbox/example3/colorbox.css
[12:26:20] File not found: resources/assets/build/site.css
[12:26:20] File not found: resources/vendor/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css
[12:26:20] File not found: resources/vendor/metisMenu/dist/metisMenu.css
[12:26:20] File not found: resources/assets/build/admin.css
[12:26:20] Finished 'styles' after 12 ms
[12:26:20] Starting 'scripts'...
[12:26:20] Merging: resources/vendor/jquery-legacy/dist/jquery.js, resources/vendor/bootstrap-sass/assets/javascripts/bootstrap.js, resources/vendor/jquery-colorbox/jquery.colorbox.js
[12:26:20] Merging: resources/vendor/datatables/media/js/jquery.dataTables.js, resources/vendor/datatables-bootstrap3-plugin/media/js/datatables-bootstrap3.js, resources/vendor/metisMenu/dist/metisMenu.js
[12:26:20] File not found: resources/vendor/jquery-legacy/dist/jquery.js
[12:26:20] File not found: resources/vendor/bootstrap-sass/assets/javascripts/bootstrap.js
[12:26:20] File not found: resources/vendor/jquery-colorbox/jquery.colorbox.js
[12:26:20] File not found: resources/vendor/datatables/media/js/jquery.dataTables.js
[12:26:20] File not found: resources/vendor/datatables-bootstrap3-plugin/media/js/datatables-bootstrap3.js
[12:26:20] File not found: resources/vendor/metisMenu/dist/metisMenu.js
[12:26:20] Finished 'scripts' after 21 ms
[12:26:20] Starting 'version'...
[12:26:20] Versioning: public/css/site.css, public/css/admin.css, public/js/site.js, public/js/admin.js
[12:26:20] Finished 'version' after 29 ms

**Comment by MakeApps** [comment]
I think after composer update it gives the errors, the problem was fixed.
Thank you!
